/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ec.admin;

import java.awt.CardLayout;

/**
 *
 * @author jiajin
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        holder = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        menu_label = new javax.swing.JLabel();
        menu_coins_button = new javax.swing.JButton();
        coins = new javax.swing.JPanel();
        coinDetailCard1 = new com.ec.admin.CoinDetailCard();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EC_Admin");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("ec_admin"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        holder.setLayout(new java.awt.CardLayout());

        menu.setBackground(new java.awt.Color(255, 255, 255));

        menu_label.setBackground(new java.awt.Color(0, 0, 0));
        menu_label.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        menu_label.setText("MENU");

        menu_coins_button.setBackground(new java.awt.Color(0, 0, 0));
        menu_coins_button.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        menu_coins_button.setText("COINS");
        menu_coins_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_coins_buttonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(menu_label))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(menu_coins_button, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(menu_label)
                .addGap(67, 67, 67)
                .addComponent(menu_coins_button, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(400, Short.MAX_VALUE))
        );

        holder.add(menu, "menu");

        javax.swing.GroupLayout coinsLayout = new javax.swing.GroupLayout(coins);
        coins.setLayout(coinsLayout);
        coinsLayout.setHorizontalGroup(
            coinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coinsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(coinDetailCard1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addContainerGap())
        );
        coinsLayout.setVerticalGroup(
            coinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coinsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(coinDetailCard1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(516, Short.MAX_VALUE))
        );

        holder.add(coins, "coins");

        getContentPane().add(holder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_coins_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_coins_buttonMouseClicked
        CardLayout cl = (CardLayout) holder.getLayout();
        cl.show(holder, "coins");
    }//GEN-LAST:event_menu_coins_buttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.ec.admin.CoinDetailCard coinDetailCard1;
    private javax.swing.JPanel coins;
    private javax.swing.JPanel holder;
    private javax.swing.JPanel menu;
    private javax.swing.JButton menu_coins_button;
    private javax.swing.JLabel menu_label;
    // End of variables declaration//GEN-END:variables
}
