/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ec.wallet;

import com.ec.admin.CoinDetailCard;
import com.ec.jna.WalletHandler;
import com.ec.main.Main;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.GroupLayout;

/**
 *
 * @author jiajin
 */
public class Wallet extends javax.swing.JFrame {

    private WalletHandler walletHandler;
    private int instanceId;
    private int coinsSize;

    /**
     * Creates new form Wallet
     */
    public Wallet(int instanceId) {
        initComponents();
        instanceId = instanceId;
        walletHandler = new WalletHandler(instanceId);
        updateCoinsSize();
        wallet_id_text.setText(Integer.toString(instanceId));
        this.setTitle(String.format("EC_Wallet_%d", instanceId));
        Main.WalletInstances.add(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        holder = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        menu_label = new javax.swing.JLabel();
        menu_coin_numb_label = new javax.swing.JLabel();
        menu_coin_numb_scp = new javax.swing.JScrollPane();
        menu_coin_numb_text = new javax.swing.JTextPane();
        menu_wallet_id_label = new javax.swing.JLabel();
        menu_wallet_id_scp = new javax.swing.JScrollPane();
        wallet_id_text = new javax.swing.JTextPane();
        menu_coins_button = new javax.swing.JButton();
        menu_transfer_button = new javax.swing.JButton();
        menu_verify_button = new javax.swing.JButton();
        verify_successed = new javax.swing.JPanel();
        verify_successed_label1 = new javax.swing.JLabel();
        verify_successed_label2 = new javax.swing.JLabel();
        verify_successed_menu_button = new javax.swing.JButton();
        coins = new javax.swing.JPanel();
        coins_label = new javax.swing.JLabel();
        coins_menu_button = new javax.swing.JButton();
        coinsScrollPane = new javax.swing.JScrollPane();
        coinsPane = new javax.swing.JPanel();
        transfer = new javax.swing.JPanel();
        transfer_label = new javax.swing.JLabel();
        transfer_wallet_id_label = new javax.swing.JLabel();
        transfer_wallet_id_scp = new javax.swing.JScrollPane();
        transfer_wallet_id_text = new javax.swing.JTextPane();
        transfer_transfer_button = new javax.swing.JButton();
        transfer_menu_button = new javax.swing.JButton();
        transferOutputMsg = new javax.swing.JLabel();
        verify = new javax.swing.JPanel();
        verify_label = new javax.swing.JLabel();
        verify_coin_id_label = new javax.swing.JLabel();
        verify_coin_id_scp = new javax.swing.JScrollPane();
        verify_coin_id_text = new javax.swing.JTextPane();
        verify_verify_button = new javax.swing.JButton();
        verify_menu_button = new javax.swing.JButton();
        verify_failed = new javax.swing.JPanel();
        verify_failed_label1 = new javax.swing.JLabel();
        verify_failed_label2 = new javax.swing.JLabel();
        verify_failed_menu_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EC_Wallet");
        setLocationByPlatform(true);

        holder.setPreferredSize(new java.awt.Dimension(500, 600));
        holder.setLayout(new java.awt.CardLayout());

        menu.setBackground(new java.awt.Color(255, 255, 255));

        menu_label.setBackground(new java.awt.Color(0, 0, 0));
        menu_label.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        menu_label.setText("MENU");

        menu_coin_numb_label.setBackground(new java.awt.Color(0, 0, 0));
        menu_coin_numb_label.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        menu_coin_numb_label.setText("COIN NUMB");

        menu_coin_numb_text.setEditable(false);
        menu_coin_numb_text.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        menu_coin_numb_text.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menu_coin_numb_text.setName(""); // NOI18N
        menu_coin_numb_scp.setViewportView(menu_coin_numb_text);
        menu_coin_numb_text.getAccessibleContext().setAccessibleName("");

        menu_wallet_id_label.setBackground(new java.awt.Color(0, 0, 0));
        menu_wallet_id_label.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        menu_wallet_id_label.setText("WALLET ID");

        wallet_id_text.setEditable(false);
        wallet_id_text.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        menu_wallet_id_scp.setViewportView(wallet_id_text);

        menu_coins_button.setText("COINS");
        menu_coins_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navToCoins(evt);
            }
        });
        menu_coins_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_coins_buttonActionPerformed(evt);
            }
        });

        menu_transfer_button.setText("TRANSFER");
        menu_transfer_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navToTransfer(evt);
            }
        });
        menu_transfer_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_transfer_buttonActionPerformed(evt);
            }
        });

        menu_verify_button.setText("VERIFY");
        menu_verify_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navToVerify(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(menu_label)
                .addGap(226, 226, 226))
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu_coin_numb_label)
                    .addComponent(menu_coin_numb_scp, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menu_wallet_id_label)
                    .addComponent(menu_wallet_id_scp, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(108, 108, 108))
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addComponent(menu_verify_button, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(menu_coins_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(menu_transfer_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(menu_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(52, 52, 52)
                .addComponent(menu_coin_numb_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu_coin_numb_scp, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menu_wallet_id_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu_wallet_id_scp, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(menu_coins_button, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menu_transfer_button, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menu_verify_button, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        holder.add(menu, "menu");

        verify_successed.setBackground(new java.awt.Color(255, 255, 255));

        verify_successed_label1.setBackground(new java.awt.Color(0, 0, 0));
        verify_successed_label1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        verify_successed_label1.setText("VERIFICATION FAILED");

        verify_successed_label2.setBackground(new java.awt.Color(0, 0, 0));
        verify_successed_label2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        verify_successed_label2.setText("YOU THE OWNER OF THE COIN");

        verify_successed_menu_button.setText("MENU");
        verify_successed_menu_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navToMenu(evt);
            }
        });

        javax.swing.GroupLayout verify_successedLayout = new javax.swing.GroupLayout(verify_successed);
        verify_successed.setLayout(verify_successedLayout);
        verify_successedLayout.setHorizontalGroup(
            verify_successedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verify_successedLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(verify_successed_label1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, verify_successedLayout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(verify_successed_label2)
                .addGap(69, 69, 69))
            .addGroup(verify_successedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(verify_successedLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(verify_successed_menu_button, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        verify_successedLayout.setVerticalGroup(
            verify_successedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verify_successedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(verify_successed_label1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(verify_successed_label2)
                .addContainerGap(522, Short.MAX_VALUE))
            .addGroup(verify_successedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(verify_successedLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(verify_successed_menu_button, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        holder.add(verify_successed, "verify_successed");
        verify_successed.getAccessibleContext().setAccessibleName("");

        coins.setBackground(new java.awt.Color(255, 255, 255));

        coins_label.setBackground(new java.awt.Color(0, 0, 0));
        coins_label.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        coins_label.setText("COINS");

        coins_menu_button.setText("MENU");
        coins_menu_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navToMenu(evt);
            }
        });
        coins_menu_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coins_menu_buttonActionPerformed(evt);
            }
        });

        coinsScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        coinsScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        coinsScrollPane.setPreferredSize(new java.awt.Dimension(435, 435));

        javax.swing.GroupLayout coinsPaneLayout = new javax.swing.GroupLayout(coinsPane);
        coinsPane.setLayout(coinsPaneLayout);
        coinsPaneLayout.setHorizontalGroup(
            coinsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
        );
        coinsPaneLayout.setVerticalGroup(
            coinsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
        );

        coinsScrollPane.setViewportView(coinsPane);

        javax.swing.GroupLayout coinsLayout = new javax.swing.GroupLayout(coins);
        coins.setLayout(coinsLayout);
        coinsLayout.setHorizontalGroup(
            coinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coinsLayout.createSequentialGroup()
                .addGroup(coinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(coinsLayout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(coins_label))
                    .addGroup(coinsLayout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(coins_menu_button, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(coinsLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(coinsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        coinsLayout.setVerticalGroup(
            coinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coinsLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(coins_label)
                .addGap(16, 16, 16)
                .addComponent(coinsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(coins_menu_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        holder.add(coins, "coins");

        transfer.setBackground(new java.awt.Color(255, 255, 255));

        transfer_label.setBackground(new java.awt.Color(0, 0, 0));
        transfer_label.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        transfer_label.setText("TRANSFER");

        transfer_wallet_id_label.setBackground(new java.awt.Color(0, 0, 0));
        transfer_wallet_id_label.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        transfer_wallet_id_label.setText("WALLET ID");

        transfer_wallet_id_text.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        transfer_wallet_id_scp.setViewportView(transfer_wallet_id_text);

        transfer_transfer_button.setText("TRANSFER");
        transfer_transfer_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transfer_transfer_buttonActionPerformed(evt);
            }
        });

        transfer_menu_button.setText("MENU");
        transfer_menu_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navToMenu(evt);
            }
        });
        transfer_menu_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transfer_menu_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout transferLayout = new javax.swing.GroupLayout(transfer);
        transfer.setLayout(transferLayout);
        transferLayout.setHorizontalGroup(
            transferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transferLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(transferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(transfer_menu_button, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transfer_label)
                    .addComponent(transfer_transfer_button, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(transferLayout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(transferOutputMsg)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(transferLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(transferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(transfer_wallet_id_label)
                    .addComponent(transfer_wallet_id_scp, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        transferLayout.setVerticalGroup(
            transferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transferLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(transfer_label)
                .addGap(52, 52, 52)
                .addComponent(transfer_wallet_id_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transfer_wallet_id_scp, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155)
                .addComponent(transferOutputMsg)
                .addGap(18, 18, 18)
                .addComponent(transfer_transfer_button, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(transfer_menu_button, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        holder.add(transfer, "transfer");

        verify.setBackground(new java.awt.Color(255, 255, 255));

        verify_label.setBackground(new java.awt.Color(0, 0, 0));
        verify_label.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        verify_label.setText("COIN VERIFICATION");

        verify_coin_id_label.setBackground(new java.awt.Color(0, 0, 0));
        verify_coin_id_label.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        verify_coin_id_label.setText("COIN ID");

        verify_coin_id_scp.setViewportView(verify_coin_id_text);

        verify_verify_button.setText("VERIFY");

        verify_menu_button.setText("MENU");
        verify_menu_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navToMenu(evt);
            }
        });

        javax.swing.GroupLayout verifyLayout = new javax.swing.GroupLayout(verify);
        verify.setLayout(verifyLayout);
        verifyLayout.setHorizontalGroup(
            verifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verifyLayout.createSequentialGroup()
                .addGroup(verifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(verifyLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(verify_label))
                    .addGroup(verifyLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(verifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(verify_coin_id_label)
                            .addComponent(verify_coin_id_scp, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(verifyLayout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addGroup(verifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(verify_menu_button, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(verify_verify_button, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        verifyLayout.setVerticalGroup(
            verifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verifyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(verify_label)
                .addGap(69, 69, 69)
                .addComponent(verify_coin_id_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(verify_coin_id_scp, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addComponent(verify_verify_button, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(verify_menu_button, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );

        holder.add(verify, "verify");

        verify_failed.setBackground(new java.awt.Color(255, 255, 255));

        verify_failed_label1.setBackground(new java.awt.Color(0, 0, 0));
        verify_failed_label1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        verify_failed_label1.setText("VERIFICATION FAILED");

        verify_failed_label2.setBackground(new java.awt.Color(0, 0, 0));
        verify_failed_label2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        verify_failed_label2.setText("YOU ARE NOT THE OWNER OF THE COIN");

        verify_failed_menu_button.setText("MENU");
        verify_failed_menu_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navToMenu(evt);
            }
        });

        javax.swing.GroupLayout verify_failedLayout = new javax.swing.GroupLayout(verify_failed);
        verify_failed.setLayout(verify_failedLayout);
        verify_failedLayout.setHorizontalGroup(
            verify_failedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verify_failedLayout.createSequentialGroup()
                .addGroup(verify_failedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(verify_failedLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(verify_failed_label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(128, 128, 128))
                    .addGroup(verify_failedLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(verify_failed_label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(19, 19, 19)))
                .addGap(13, 13, 13))
            .addGroup(verify_failedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(verify_failedLayout.createSequentialGroup()
                    .addGap(184, 184, 184)
                    .addComponent(verify_failed_menu_button, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(203, Short.MAX_VALUE)))
        );
        verify_failedLayout.setVerticalGroup(
            verify_failedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verify_failedLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(verify_failed_label1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(verify_failed_label2)
                .addContainerGap(514, Short.MAX_VALUE))
            .addGroup(verify_failedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(verify_failedLayout.createSequentialGroup()
                    .addGap(272, 272, 272)
                    .addComponent(verify_failed_menu_button, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(273, Short.MAX_VALUE)))
        );

        holder.add(verify_failed, "verify_failed");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(holder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(holder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void navToCoins(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navToCoins
        CardLayout cl = (CardLayout) holder.getLayout();
        cl.show(holder, "coins");
    }//GEN-LAST:event_navToCoins

    private void navToTransfer(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navToTransfer
        CardLayout cl = (CardLayout) holder.getLayout();
        cl.show(holder, "transfer");
    }//GEN-LAST:event_navToTransfer

    private void navToVerify(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navToVerify
        CardLayout cl = (CardLayout) holder.getLayout();
        cl.show(holder, "verify");
    }//GEN-LAST:event_navToVerify

    private void navToMenu(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navToMenu
        CardLayout cl = (CardLayout) holder.getLayout();
        cl.show(holder, "menu");
    }//GEN-LAST:event_navToMenu

    private void menu_coins_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_coins_buttonActionPerformed
        List<String> coinsData = walletHandler.sp_getWalletMiniData(); // get coins data..

        CardLayout cl = (CardLayout) holder.getLayout(); // show coins page
        cl.show(holder, "coins");

        javax.swing.GroupLayout coinsPanelLayout = new javax.swing.GroupLayout(coinsPane);
        coinsPane.setLayout(coinsPanelLayout);

        GroupLayout.ParallelGroup horizontalPG = coinsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING);

        ArrayList<Component> componentList = new ArrayList();
        for (int i = 0; i < coinsData.size(); i++) {
            CoinDetailCard card = new CoinDetailCard(i + 1, coinsData.get(i));
            componentList.add(card);
            horizontalPG.addComponent(card, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE);
        }

        coinsPanelLayout.setHorizontalGroup(
                coinsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(coinsPanelLayout.createSequentialGroup()
                                .addContainerGap().addGroup(horizontalPG)));

        GroupLayout.SequentialGroup verticalSG = coinsPanelLayout.createSequentialGroup();
        for (int i = coinsData.size() - 1; i >= 0; i--) {
            verticalSG.addComponent(componentList.get(i), javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE);
            if (i != 0) {
                verticalSG.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED);
            }
        }

        coinsPanelLayout.setVerticalGroup(
                coinsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(verticalSG));

        coinsScrollPane.setViewportView(coinsPane);
    }//GEN-LAST:event_menu_coins_buttonActionPerformed

    private void coins_menu_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coins_menu_buttonActionPerformed
        CardLayout cl = (CardLayout) holder.getLayout(); // show coins page
        cl.show(holder, "menu");
        updateCoinsSize();
    }//GEN-LAST:event_coins_menu_buttonActionPerformed

    private void menu_transfer_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_transfer_buttonActionPerformed
        CardLayout cl = (CardLayout) holder.getLayout(); // show coins page
        cl.show(holder, "transfer");
    }//GEN-LAST:event_menu_transfer_buttonActionPerformed

    private void transfer_menu_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transfer_menu_buttonActionPerformed
        CardLayout cl = (CardLayout) holder.getLayout(); // show coins page
        cl.show(holder, "transfer");
        updateCoinsSize();
    }//GEN-LAST:event_transfer_menu_buttonActionPerformed

    private void transfer_transfer_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transfer_transfer_buttonActionPerformed
        int toWalletId;
        try {
            toWalletId = Integer.parseInt(transfer_wallet_id_text.getText());
        } catch (NumberFormatException e) {
            transferOutputMsg.setText("walletId must be an Integer");
            return;
        }
        if (WalletHandler.RetrieveOrCreateWalletPointer(toWalletId, false) == null) {
            transferOutputMsg.setText("walletId none exist");
        } else {
            String output = walletHandler.transfer(WalletHandler.RetrieveOrCreateWalletPointer(toWalletId, false));
            if (output.contains("received y_transfer_completed from")) {
                transferOutputMsg.setText("done");
                Main.RefreshWalletsCoinsSize();
            } else {
                transferOutputMsg.setText("err");
            }
        }
    }//GEN-LAST:event_transfer_transfer_buttonActionPerformed

    public void updateCoinsSize() {
        coinsSize = walletHandler.sp_getWalletMiniData().size();
        menu_coin_numb_text.setText(Integer.toString(coinsSize));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel coins;
    private javax.swing.JPanel coinsPane;
    private javax.swing.JScrollPane coinsScrollPane;
    private javax.swing.JLabel coins_label;
    private javax.swing.JButton coins_menu_button;
    private javax.swing.JPanel holder;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel menu_coin_numb_label;
    private javax.swing.JScrollPane menu_coin_numb_scp;
    private javax.swing.JTextPane menu_coin_numb_text;
    private javax.swing.JButton menu_coins_button;
    private javax.swing.JLabel menu_label;
    private javax.swing.JButton menu_transfer_button;
    private javax.swing.JButton menu_verify_button;
    private javax.swing.JLabel menu_wallet_id_label;
    private javax.swing.JScrollPane menu_wallet_id_scp;
    private javax.swing.JPanel transfer;
    private javax.swing.JLabel transferOutputMsg;
    private javax.swing.JLabel transfer_label;
    private javax.swing.JButton transfer_menu_button;
    private javax.swing.JButton transfer_transfer_button;
    private javax.swing.JLabel transfer_wallet_id_label;
    private javax.swing.JScrollPane transfer_wallet_id_scp;
    private javax.swing.JTextPane transfer_wallet_id_text;
    private javax.swing.JPanel verify;
    private javax.swing.JLabel verify_coin_id_label;
    private javax.swing.JScrollPane verify_coin_id_scp;
    private javax.swing.JTextPane verify_coin_id_text;
    private javax.swing.JPanel verify_failed;
    private javax.swing.JLabel verify_failed_label1;
    private javax.swing.JLabel verify_failed_label2;
    private javax.swing.JButton verify_failed_menu_button;
    private javax.swing.JLabel verify_label;
    private javax.swing.JButton verify_menu_button;
    private javax.swing.JPanel verify_successed;
    private javax.swing.JLabel verify_successed_label1;
    private javax.swing.JLabel verify_successed_label2;
    private javax.swing.JButton verify_successed_menu_button;
    private javax.swing.JButton verify_verify_button;
    private javax.swing.JTextPane wallet_id_text;
    // End of variables declaration//GEN-END:variables
}
